spring:
  thymeleaf:
    prefix: file:src/main/resources/templates/
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:database
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        ddl-auto: create-drop
        format_sql: true

security:
  jwt:
    token:
      secret-key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIiLCJuYW1lIjoiSm9obiBEb2UiLCJpYXQiOjE1MTYyMzkwMjJ9.ih1aovtQShabQ7l0cINw4k1fagApg3qLWiB8Kt59Lno
      expire-length: 3600000

payment:
  toss:
    secret-key: test_gsk_docs_OaPz8L5KdmQXkzRz3y47BMw6
    url:
      base: https://api.tosspayments.com
      payment-confirm: /v1/payments/confirm
    time-out:
      connection: 3
      read: 30

logging:
  level:
    org.hibernate.orm.jdbc.bind: trace
